# This is a basic workflow that is manually triggered

name: Run prono for a match

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      country2:
        description: 'First country'
        # Default value if no value is explicitly provided
        default: ''
        # Input has to be provided for the workflow to run
        required: true
      country1:
        description: 'Second country'
        # Default value if no value is explicitly provided
        default: ''
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  run_prono:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run scripts to compute prono for a match
      run: ./run_scripts.sh ${{ github.event.inputs.country1 }} ${{ github.event.inputs.country2 }}
    - name: Push new prono
      run: |
        git config --global user.name 'nsutter'
        git config --global user.email 'suttercyril.sutternicolas@gmail.com'
        git push
